[build]
# When compiling from source, you almost always want a full stage 2 build
build-stage = 2

[llvm]
# Most users installing from source want to build all parts of the project from source, not just rustc itself.
download-ci-llvm = false
targets = "X86"
cflags = "-march=x86-64-v2"
cxxflags = "-march=x86-64-v2"